### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by k3fjeee** [www5226448/web3s#8]
![image](https://user-images.githubusercontent.com/85024728/161798248-c61eed5a-7728-4df5-bf9e-fa274f987d73.png)
![image](https://user-images.githubusercontent.com/85024728/161798386-34fa9719-8ad1-4a5a-8fad-d3de571a57dc.png)

`ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-16' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=TypeError("'<' not supported between instances of 'coroutine' and 'int'")>
Traceback (most recent call last):
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\xyz\Desktop\main.py", line 92, in slogs
    b = w3.fromWei(b, 'ether')
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\site-packages\eth_utils\currency.py", line 51, in from_wei
    if number < MIN_WEI or number > MAX_WEI:
TypeError: '<' not supported between instances of 'coroutine' and 'int'
C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py:1891: RuntimeWarning: coroutine 'Eth.getBalance' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
`

**Comment by www5226448** [comment]
please plaste the complete script
It appeared that the corontine has not been awaited or the comparison operator error.
